ru-RU grammar corrections
Mirsario/TerrariaOverhaul pull request #98
Opened 2022-06-01 16:13 UTC by Snoop1CattZ69

Some strings has grammar mistakes which may confuse some players, the most of mistakes looks like strings which translated by google translator :)

2022-06-01 22:32 UTC, Mirsario requested changes
I am a native Russian speaker, so there were no machine translations involved. More so it's just that I don't particularly enjoy translating things myself.

Two notes below, everything besides them is nice.

2022-06-01 22:32 UTC, Mirsario commented on Localization/ru-RU.hjson
> +					Description: "Переключение горизонтальго ускорения, максимальной скорости и разгона при беге."
Игнорируя две новых опечатки, вот эти предложения в основном неверны. В моде присутствует много разных изменений, связанных с вещами которые многие бы связали с ускорением - поэтому там `изменения` было написано в множественном числе. Описания, тем временем, специально упоминали трение, т.к., насколько я помню, оно напрямую влияет на ускорение в некоторых контекстах.
Перефразировка последних слов про разгон однако лучше.

> Ignoring the two new typos on the first and last lines, these are mostly wrong. In the mod, there are multiple different changes related to what's treated by players as acceleration, therefore DisplayNames use plural words. And the descriptions are meant indeed to say friction, not acceleration. Friction, or de-acceleration, directly affects acceleration, iirc.
The last 'при беге' bit is worded better though, gud.

2022-06-01 22:32 UTC, Mirsario commented on Localization/ru-RU.hjson
> +					DisplayName: "Включить поворот головы персонажей игроков"
Это подкреплено каким-то специальным правилом? Персонаж здесь не один, а предложенная версия звучит для меня как английское 'Rotate the head of players' characters' (там звучит как будто речь о главе.)

> Is this supported by some specific rule? The right sides are all plural, and the suggested version sounds like the English 'Rotate the head of players' characters' (sounds like it's about a boss.)

2022-06-01 23:51 UTC, Snoop1CattZ69 commented on Localization/ru-RU.hjson
> +					Description: "Переключение горизонтальго ускорения, максимальной скорости и разгона при беге."
Хоть бы где то пометки оставлял что ты всё таки ру)

по поводу `изменения` да я тут тупанул малёха, голова по попе пошла.

по поводу `трения` сам понимаешь что восприятие данного слова у многих либо размытое либо вообще недопонимание, ускорение банально понятнее.

2022-06-01 23:55 UTC, Snoop1CattZ69 commented on Localization/ru-RU.hjson
> +					Description: "Переключение горизонтальго ускорения, максимальной скорости и разгона при беге."
_отсылка к моей сонной голове_

Почему бы тогда вместо `изменения` не написать `модификацию(и)` ? Это намного понятнее, что мод напрямую изменит механику ускорения персонажа.

2022-06-01 23:56 UTC, Snoop1CattZ69 commented on Localization/ru-RU.hjson
> +					DisplayName: "Включить поворот головы персонажей игроков"
РЕВЕРТИРУЕМ

2022-06-01 23:59 UTC, Snoop1CattZ69 commented
Check new changes, iww.

2022-06-03 21:22 UTC, Mirsario approved these changes

2022-06-03 21:22 UTC, merged